# Generated by Django 4.2 on 2024-09-07 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profile_picture',
            field=models.ImageField(blank=True, default='static/image/default_profile.png', upload_to='media/%Y/%M/%D/'),
        ),
    ]
